# Catppuccin Latte (Sweet Mauve Remix)
# Vibe: Blackberry jam on warm cream. Light, crisp, and sweet.

[colors]
background = #bcc0ccff
card_bg = #eff1f5ff
card_selected = #ffffffff
text_color = #4c4f69ff
subtext_color = #6c6f85ff
border_color = #8839efff
bundle_bg = #dce0e8ff
badge_bg = #652aafff
badge_text_color = #ffffffff
badge_bg_selected = #8839efff
badge_text_color_selected = #eff1f5ff
