# Catppuccin Frappé (Mint/Luminous Green Edition)
# Vibe: Cool slate base with a high-energy, glowing green accent.
# Self Made 

[colors]
background = #292c3cff
card_bg = #303446ff
card_selected = #414559ff
text_color = #c6d0f5ff
subtext_color = #838ba7ff
border_color = #c3e88dff
bundle_bg = #303446cc
badge_bg = #95b36bff
badge_text_color = #292c3cff
badge_bg_selected = #c3e88dff
badge_text_color_selected = #292c3cff
