# Dracula Theme
# https://draculatheme.com

[colors]
background = #282a36ff
card_bg = #44475aff
card_selected = #6272a4ff
text_color = #f8f8f2ff
subtext_color = #bfbfbfff
border_color = #ab76f5ff
bundle_bg = #44475acc
badge_bg = #7e57b5ff
badge_text_color = #f8f8f2ff
badge_bg_selected = #ab76f5ff
badge_text_color_selected = #282a36ff

