# Gruvbox Dark Theme
# https://github.com/morhetz/gruvbox

[colors]
background = #282828ff
card_bg = #3c3836ff
card_selected = #665c54ff
text_color = #ebdbb2ff
subtext_color = #a89984ff
border_color = #fe8019ff
bundle_bg = #32302fff 
badge_bg = #d65d0eff
badge_text_color = #f9f5d7ff
badge_bg_selected = #fe8019ff
badge_text_color_selected = #282828ff
