# Noctalia theme for snappy-switcher

[colors]
background = #1a1b26aa
card_bg = #24283baa
card_selected =  #333954ff
text_color = #cfddfcdd
subtext_color =  #cfddfccc
border_color =  #5d6682ff
bundle_bg = #4f00dfff
badge_bg =  #bb9af7aa
badge_text_color = #16161eaa
badge_bg_selected = #bb9af7cc
badge_text_color_selected = #16161eff