# Stormlight Slate
# Vibe: A tranquil, overcast night base struck by calm, static-lightning yellow.
# Self Made 

[colors]
background = #292c3cff
card_bg = #303446ff
card_selected = #414559ff
text_color = #ffffffff
subtext_color = #838ba7ff
border_color = #f7f36dff
bundle_bg = #303446cc
badge_bg = #b8b451ff
badge_text_color = #292c3cff
badge_bg_selected = #f7f36dff
badge_text_color_selected = #292c3cff
