[pyprland]
plugins = [
  "scratchpads",
  "fetch_client_menu",
  "magnify",
  "expose",
  "shortcuts_menu",
  "toggle_special",
]

[scratchpads.term]
command = "kitty --class kitty_dropdown"
animation = "fromTop"
unfocus = "hide"
excludes = "*"
lazy = true
multi = false

[scratchpads.volume]
command = "pavucontrol"
animation = "fromLeft"
class = "volume_sidemenu"
size = "40% 70%"
unfocus = "hide"
excludes = "*"
lazy = true
margin = 90
multi = false
