# https://alacritty.org/config-alacritty.html

[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]
live_config_reload = true
working_directory = "~/Downloads"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500

[cursor.style]
shape = "Underline"
blinking = "On"

[env]
TERM = "xterm-256color"
SHELL = "fish"

[terminal]
shell = "fish"
osc52 = "CopyPaste"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[keyboard]

bindings = [

  # Copy/Paste
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" },

  # Font size
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Control", action = "IncreaseFontSize" },

  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Control", action = "DecreaseFontSize" },

  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Numpad0", mods = "Control", action = "ResetFontSize" },
]
