[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/gbp5wpg9yywgmbd8yajxqpdknwkr1qbw-noctalia-shell-2026-06-05_2461f87/share/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/leonne/.cache/noctalia/placeholder.json"

