code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.project-manager
code --install-extension arrterian.nix-env-selector
code --install-extension astro-build.astro-vscode
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bodil.file-browser
code --install-extension catppuccin.catppuccin-vsc
code --install-extension charliermarsh.ruff
code --install-extension chrischinchilla.vscode-pandoc
code --install-extension christian-kohler.path-intellisense
code --install-extension codeium.windsurfpyright
code --install-extension codezombiech.gitignore
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ericsia.pythonsnippets3
code --install-extension esbenp.prettier-vscode
code --install-extension fill-labs.dependi
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension gruntfuggly.todo-tree
code --install-extension humao.rest-client
code --install-extension irongeek.vscode-env
code --install-extension james-yu.latex-workshop
code --install-extension jeff-hykin.better-nix-syntax
code --install-extension jnoortheen.nix-ide
code --install-extension joshmu.periscope
code --install-extension kamadorueda.alejandra
code --install-extension kevinrose.vsc-python-indent
code --install-extension kylinideteam.cmake-intellisence
code --install-extension llvm-vs-code-extensions.vscode-clangd
code --install-extension magicstack.magicpython
code --install-extension mathiaskes.latex-math-preview-jupyter
code --install-extension mathiassoeholm.markdown-link-updater
code --install-extension mechatroner.rainbow-csv
code --install-extension meganrogge.template-string-converter
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mkhl.direnv
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.hexeditor
code --install-extension mshr-h.veriloghdl
code --install-extension myriad-dreamin.tinymist
code --install-extension nefrob.vscode-just-syntax
code --install-extension njpwerner.autodocstring
code --install-extension nonoroazoro.syncing
code --install-extension nvarner.typst-lsp
code --install-extension phil294.git-log--graph
code --install-extension pinage404.nix-extension-pack
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension pkief.material-icon-theme
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension rust-lang.rust-analyzer
code --install-extension shardulm94.trailing-spaces
code --install-extension solomonkinard.git-search
code --install-extension stkb.rewrap
code --install-extension stylelint.vscode-stylelint
code --install-extension sumneko.lua
code --install-extension surv.typst-math
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension tecosaur.latex-utilities
code --install-extension teros-technology.teroshdl
code --install-extension teticio.python-envy
code --install-extension tomoki1207.pdf
code --install-extension torn4dom4n.latex-support
code --install-extension twxs.cmake
code --install-extension unifiedjs.vscode-mdx
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vsls-contrib.gitdoc
code --install-extension waderyan.gitblame
code --install-extension wmaurer.change-case
code --install-extension xaver.clang-format
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zainchen.json
code --install-extension zhwu95.riscv
code --install-extension ziglang.vscode-zig
