[language-server.hyprls]
command = "hyprls"

[[language]]
name = "hyprlang"
language-servers = ["hyprls"]
auto-format = true

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.copilot]
command = "helix-gpt"
args = [
  "--handler",
  "copilot",
  "--copilotApiKey",
  "your_api_key",    # FIXME
]

[[language]]
name = "python"
language-servers = [{ name = "pylsp", except-features = ["format"] }, "ruff"]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[language-server.gopls.config]
gofumpt = true

[[language]]
auto-format = true
name = "nix"
formatter = { command = "alejandra", args = ["-"] }

[[language]]
auto-format = true
name = "latex"
formatter = { command = "tex-fmt", args = ["-"] }

[language-server.lsp-ai]
command = "lsp-ai"
args = ["--stdio"]

[[language]]
name = "go"
language-servers = ["gopls"]
formatter = { command = "gofumpt", args = ["-w", "-"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
formatter = { command = "rustfmt", args = ["--emit", "stdout"] }
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "html"
language-servers = ["emmet-lsp", "vscode-html-language-server"]
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
indent = { tab-width = 4, unit = "   " }
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "config"
scope = "source.conf"
file-types = ["conf"]
comment-token = "#"
roots = []
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "typst"
formatter = { command = "typstfmt", args = ["--output", "-"] }
auto-format = true

[[language]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true
